name: Terraform Deployments

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Authenticate to GCP
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "${GOOGLE_CREDENTIALS}" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json

    - name: Set up Terraform Cloud authentication
      env:
        TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      run: |
        mkdir -p ~/.terraform.d
        echo "{\"credentials\": {\"app.terraform.io\": {\"token\": \"${TFE_TOKEN}\"}}}" > ~/.terraform.d/credentials.tfrc.json
        chmod 600 ~/.terraform.d/credentials.tfrc.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
